FROM apache/airflow:2.9.3

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openjdk-17-jdk \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    yfinance==0.2.52 \
    pandas==2.2.3 \
    SQLAlchemy==2.0.36 \
    PyMySQL==1.1.1 \
    pyspark==3.5.2 \
    python-dotenv==1.0.1
